### ISSUE TITLE
Next version bump for Django 3.2 support

### ISSUE THREAD

**Issue by mariajgrimaldi** [django-cms/django-classy-tags#62]
Hi there! I opened this issue to keep track of the next version bump that includes support for Django 3.2.

Many thanks for considering my request.

**Comment by mariajgrimaldi** [comment]
cc @marksweb :)

**Comment by marksweb** [comment]
@mariajgrimaldi this release is now very nearly ready. I'm coordinating it alongside django-sekizai

**Comment by marksweb** [comment]
Version 3 is now available
