### ISSUE TITLE
I probably should no longer have PyPI Access

### ISSUE THREAD

**Issue by ojii** [django-cms/django-classy-tags#82]
Hi, just got an email from PyPI that django-classy-tags is a "critical project". I still have "Owner" permissions on this project, but haven't contributed to this project (or even done any Django) in years. It's probably best if you remove my permissions from PyPI for this package.

**Comment by marksweb** [comment]
@ojii i can take care of that. I think you're still on quite a lot of our projects. Shall I remove you from all?

**Comment by ojii** [comment]
> Shall I remove you from all?

Probably for the best.
